theme: jekyll-theme-cayman
title: Vicente Opaso
description: Senior Frontend Developer — JavaScript Obsessed
cvdownload: https://github.com/vicenteopaso/vicenteopaso/blob/f3b7fd9ca7eef5a90e59e4c602ef249b574b5c5c/assets/Vicente_Opaso_Resume.pdf
linkedin: https://www.linkedin.com/in/vicenteopaso/
twitter: https://twitter.com/vicenteopaso
github: https://github.com/vicenteopaso
