# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: github-pages  # <-- add this if the secret lives in that environment
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - id: pages
        uses: actions/configure-pages@v5

      - name: Inject Google Maps API key into Jekyll config
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          set -eo pipefail
          FILE="_config.yml"
          KEY="google_maps_api_key"
          VAL="${GOOGLE_MAPS_API_KEY:-}"

          if [ -z "$VAL" ]; then
            echo "ERROR: GOOGLE_MAPS_API_KEY is empty/unavailable. If this secret is in an Environment, make sure this job uses 'environment: github-pages' OR move it to repo-level secrets."
            exit 1
          fi

          if grep -qE "^[[:space:]]*${KEY}:" "$FILE"; then
            sed -i "s|^[[:space:]]*${KEY}:.*|${KEY}: \"${VAL}\"|" "$FILE"
          else
            printf "\n%s: \"%s\"\n" "$KEY" "$VAL" >> "$FILE"
          fi

          echo "Injected '${KEY}' into ${FILE} (value masked)."

      - name: Build with Jekyll (prod cfg)
        run: |
          bundle exec jekyll build \
            --config _config.yml \
            --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
