# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - id: pages
        uses: actions/configure-pages@v5

      - name: Assert Maps key present
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          if [ -z "${{ GOOGLE_MAPS_API_KEY }}" ]; then
            echo "GOOGLE_MAPS_API_KEY missing."
            exit 1
          fi
          echo "Key length: ${{ GOOGLE_MAPS_API_KEY }}"

      - name: Create prod config
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          cat > _config_prod.yml <<EOF
          google_maps_api_key: "${GOOGLE_MAPS_API_KEY}"
          EOF

      - name: Build with Jekyll (prod cfg)
        run: bundle exec jekyll build --config _config.yml,_config_prod.yml --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Verify key made it into _site
        run: |
          if grep -R --include="*.html" "{{ site.google_maps_api_key" _site; then
            echo "Liquid not rendered; add front matter to including page/layout."
            exit 1
          fi
          if grep -R --include="*.html" "GOOGLE_MAPS_API_KEY" _site; then
            echo "Placeholder still present; include not processed."
            exit 1
          fi
          grep -R --include="*.html" 'maps.googleapis.com/maps/api/js?key=' _site || exit 1

      - name: Remove symlinks before upload
        run: find _site -type l -delete

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
